### ISSUE TITLE
[BUG] Onshout looping

### ISSUE THREAD

**Issue by ItsMrReals** [suufi/noblox.js#206] opened 2020-10-19 17:14 UTC
## Before posting a bug, be sure that someone else has not posted it already and it is an actual bug with noblox.js and not other frameworks like discord.js

**Describe the bug**
The onshout function is looping

**To Reproduce**
1. Make an onshout function
2. Start the server
3. Shout something 
4. See the loop

**Expected behavior**
To not loop.

**Screenshots**
https://cdn.iharrblx.xyz/Discord_PoEiQcN1RR.png

**Additional context**

**Comment by ItsMrReals** [comment] 2020-10-19 17:14
By the way, this happened when just doing this as a console.log, with no discord

**Comment by efewqefwfd** [comment] 2020-10-24 17:15
I tried this myself and it worked as expected, are you on the latest version? If so, can you please send code that will reproduce the issue?

**Comment by Ashp116** [comment] 2020-10-28 17:49
Well I am getting the error `Unhandled rejection RequestError: Error: socket hang up` for the OnShout Event

**Comment by ItsMrReals** [comment] 2020-10-28 18:00
That’s the issue I’m getting, is this just me

**Comment by Ashp116** [comment] 2020-10-28 18:01
Its not looping but I get that error

**Comment by Ashp116** [comment] 2020-10-28 18:01
is it possible to see your code? to find the prob?

**Comment by ItsMrReals** [comment] 2020-10-28 18:01
When I get home

**Comment by suufi** [comment] 2020-11-09 00:08
Can you show your code? This is definitely working as expected; I don't see any looping on my code sample.

**Comment by Ashp116** [comment] 2020-11-09 00:12
Well the event doesn't work as intended because when I run my discord bot, and after like 3 min or less I get a error called `Unhandled rejection RequestError: Error: socket hang up`. And yes sometimes it does loop for me too

**Comment by suufi** [comment] 2020-11-09 18:10
Where are you running this Discord bot? Do you have a reproducible code sample?

**Comment by Ashp116** [comment] 2020-11-11 23:18
I do not as of now because I was trying to make a work around. But ultimately I get that error every time I use the event.

**Comment by chexburger** [comment] 2020-12-19 02:15
@Ashp116 
The socket hang up error traces back to request.js, a deprecated package. This may be the result of the package or noblox code lacking an appropriate catch for these errors (stack trace only mentions request).  As far as I'm aware, as long as these events are being used, there is no workaround from the errors. These errors do not cause a program crash and the program should proceed as usual.

**Comment by Ashp116** [comment] 2020-12-19 02:17
well I made an event that uses `setInterval()` for checking data. I am not sure if I could use that over noblox's OnShout()

**Comment by Neztore** [comment] 2021-05-07 18:56
Can't reproduce and the author went quiet - probably should've closed it before now

**Closed by Neztore** 2021-05-07 18:56 UTC
Labels: question
