### ISSUE TITLE
Group Functions sometimes don't work due to captchas

### ISSUE THREAD

**Issue by efewqefwfd** [suufi/noblox.js#14] opened 2018-06-08 07:53 UTC
I use Group Functions such as setRank and it says "Invalid permissions". I go and rank someone a few times to farm some captchas, then it works! This means, captchas a preventing the bot and this is a bug needing to be fixed. You could possibly use https://www.npmjs.com/package/deathbycaptcha to solve the captchas and the issue can be resolved. This may also have to do with the Group Events not working, as Roblox is adding captchas EVERYWHERE.

**Comment by suufi** [comment] 2018-06-08 22:07
It's not a bug and it can't be fixed without me breaking the bank.

**Closed by suufi** 2018-06-08 22:07 UTC

**Comment by Helpememsa** [comment] 2019-04-14 00:22
'npm' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Kenner-G** [comment] 2019-07-08 15:04
wait huh... setting player ranks result in captchas?  I thought only group joins did
